//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholeSale
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountReceive
    {
        public int arId { get; set; }
        public int docId { get; set; }
        public Nullable<int> refDocId { get; set; }
        public Nullable<int> invoiceId { get; set; }
        public Nullable<decimal> creditAmont { get; set; }
        public Nullable<decimal> debitAmount { get; set; }
        public Nullable<int> paymentType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> pay { get; set; }
        public Nullable<decimal> change { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string createBy { get; set; }
        public System.DateTime createTime { get; set; }
        public string editBy { get; set; }
        public System.DateTime editTime { get; set; }
        public string compCode { get; set; }
        public string branchCode { get; set; }
    }
}
