//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholeSale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int branchID { get; set; }
        public string compCode { get; set; }
        public string branchCode { get; set; }
        public string branchName { get; set; }
        public string detail { get; set; }
        public Nullable<int> orderBy { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string createBy { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string updateBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    }
}
