//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholeSale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int deviceId { get; set; }
        public string deviceName { get; set; }
        public string deviceType { get; set; }
        public string deviceSerialNo { get; set; }
        public Nullable<int> curValue { get; set; }
        public Nullable<int> tolValue { get; set; }
        public Nullable<bool> isOpen { get; set; }
        public Nullable<System.DateTime> expireDate { get; set; }
        public Nullable<int> orderBy { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string createBy { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string editBy { get; set; }
        public Nullable<System.DateTime> editDate { get; set; }
        public string compCode { get; set; }
        public string branchCode { get; set; }
    }
}
