//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholeSale
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentLine()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int DocumentLineId { get; set; }
        public int DocumentId { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<int> invoiceId { get; set; }
        public string invoiceNo { get; set; }
        public int productId { get; set; }
        public string productName { get; set; }
        public string unit { get; set; }
        public decimal unitPrice { get; set; }
        public decimal qty { get; set; }
        public decimal amount { get; set; }
        public int vatType { get; set; }
        public decimal dcPrice { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string createBy { get; set; }
        public System.DateTime createTime { get; set; }
        public string editBy { get; set; }
        public System.DateTime editTime { get; set; }
        public string compCode { get; set; }
        public string branchCode { get; set; }
        public decimal vat { get; set; }
        public decimal amountIncludeVat { get; set; }
        public Nullable<decimal> discountUnit { get; set; }
        public Nullable<decimal> discountTotal { get; set; }
    
        public virtual Document Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
