//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholeSale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.DocumentLines = new HashSet<DocumentLine>();
        }
    
        public int documentId { get; set; }
        public string documentNo { get; set; }
        public int orderId { get; set; }
        public int customerId { get; set; }
        public int vendorId { get; set; }
        public bool isOrder { get; set; }
        public bool isTax { get; set; }
        public int paidType { get; set; }
        public string remark { get; set; }
        public int status { get; set; }
        public bool isActive { get; set; }
        public string createBy { get; set; }
        public System.DateTime createTime { get; set; }
        public string editBy { get; set; }
        public System.DateTime editTime { get; set; }
        public string compCode { get; set; }
        public string branchCode { get; set; }
        public decimal totalVat { get; set; }
        public decimal totalLineDiscount { get; set; }
        public decimal totalPriceBeforeDiscount { get; set; }
        public decimal endDiscount { get; set; }
        public decimal totalDiscount { get; set; }
        public decimal totalPriceAfterDiscountLine { get; set; }
        public decimal totalPriceAfterAllDiscount { get; set; }
        public decimal totalPriceBeforeVat { get; set; }
        public decimal qty { get; set; }
        public int rev { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentLine> DocumentLines { get; set; }
    }
}
