//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholeSale
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int orderLineId { get; set; }
        public int orderId { get; set; }
        public string orderNo { get; set; }
        public string productCode { get; set; }
        public string productName { get; set; }
        public string unit { get; set; }
        public decimal unitPrice { get; set; }
        public decimal qty { get; set; }
        public decimal totalPrice { get; set; }
        public int vatType { get; set; }
        public decimal vatPrice { get; set; }
        public decimal dcPrice { get; set; }
        public bool isActive { get; set; }
        public string createBy { get; set; }
        public System.DateTime createTime { get; set; }
        public string editBy { get; set; }
        public System.DateTime editTime { get; set; }
        public string compCode { get; set; }
        public string branchCode { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
