//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholeSale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int productId { get; set; }
        public string productCode { get; set; }
        public string productName { get; set; }
        public Nullable<int> productTypeId { get; set; }
        public Nullable<int> productRefId { get; set; }
        public int categoryId { get; set; }
        public int typeId { get; set; }
        public int groupId { get; set; }
        public int unitId { get; set; }
        public Nullable<decimal> minPrice { get; set; }
        public Nullable<decimal> maxPrice { get; set; }
        public Nullable<decimal> previousPrice { get; set; }
        public decimal price { get; set; }
        public Nullable<bool> reqSn { get; set; }
        public Nullable<bool> ctlExpDate { get; set; }
        public Nullable<int> image1Id { get; set; }
        public Nullable<int> image2Id { get; set; }
        public Nullable<int> image3Id { get; set; }
        public Nullable<int> orderBy { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string createBy { get; set; }
        public System.DateTime createTime { get; set; }
        public string editBy { get; set; }
        public System.DateTime editTime { get; set; }
        public string compCode { get; set; }
        public string branchCode { get; set; }
    
        public virtual Balance Balance { get; set; }
        public virtual Category Category { get; set; }
        public virtual Group Group { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
