//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholeSale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transactionId { get; set; }
        public int documentLineId { get; set; }
        public int productId { get; set; }
        public Nullable<int> invoiceLineId { get; set; }
        public decimal price { get; set; }
        public int movementTypeId { get; set; }
        public decimal qty { get; set; }
        public string unit { get; set; }
        public string createBy { get; set; }
        public System.DateTime createTime { get; set; }
        public string editBy { get; set; }
        public System.DateTime editTime { get; set; }
        public string compCode { get; set; }
        public string branchCode { get; set; }
    
        public virtual DocumentLine DocumentLine { get; set; }
        public virtual MovementType MovementType { get; set; }
        public virtual Product Product { get; set; }
    }
}
